---
title: "Untitled"
author: "Allie Cole"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dataRetrieval)
library(tidyverse)
library(metajam)
library(here)
```

### API LAB FROM CLASS 

#### Exercise 1 Using `dataRetrieval` 


```{r}
siteNumber <- "11118500"
parameterCd <- "00060" #this is the discharge number
startDate <- "1988-10-01" #if you just do "" then it will find the start date 
endDate <- "2021-07-03" #birthday heck ya 

discharge <- readNWISdv(siteNumber, 
                    parameterCd, 
                    startDate, 
                    endDate) #reading in all the info above 

names(discharge)
dischare_clean <- renameNWISColumns(discharge) #takes the names
names(dischare_clean)
```

```{r}
ggplot(data = dischare_clean, aes(x = Date, y = Flow)) +
  geom_line()
```

### Exercise 2 Using Metajam 

```{r, eval=FALSE}
#make sure metajam is installed

data_obj <- "https://cn.dataone.org/cn/v2/resolve/urn:uuid:7fc6f6db-c5ea-426a-a743-1f2edafb43b8"
path <- "~/Documents/MEDS/fall_term/EDS213/EDS213_API_lab"

download_d1_data(data_url = data_obj, path = path)

```

```{r}
#getting the data 

lang_data <- read_d1_files("~/Documents/MEDS/fall_term/EDS213/EDS213_API_lab/doi_10.5063_F1CJ8BPH__household_language__csv")
```

#### Plotting the data 

```{r}
plot_data <- lang_data$data %>% 
  filter(Year >= 2009,
         Year <= 2015) %>% 
  mutate(percent_english = (speak_only_english/total)) %>% 
  select(Year, SASAP.Region, city, total, speak_only_english, percent_english) %>% 
  group_by(Year) %>% 
  summarise(av_eng_pre = mean(percent_english, na.rm = TRUE))

ggplot(data = plot_data, aes(x = Year, y =av_eng_pre)) +
  geom_line()

```

**This is the end of what we did in class** 

### Assignment 2.1

```{r}
#adding more data one to what we did in class so we can compare 
parameterCd_vt <- "00060" #this is the discharge number
startDate_vt <- "2021-10-03" #if you just do "" then it will find the start date 
endDate_vt <- "2021-10-04" 

discharge <- readNWISuv(siteNumber = c("11118500","11113500"), 
                    parameterCd_vt, 
                    startDate_vt, 
                    endDate_vt) %>% 
  renameNWISColumns(discharge) #takes the names


ggplot(data = discharge, aes(x= dateTime, y = Flow_Inst)) +
  geom_point(aes(color = site_no)) +
  scale_color_discrete(name = "Site Name", labels = c("Santa Paula", "Ventura"))

```
2. The best way to query multiple data sets is to concatenate them, put them into a vector and upload them together
3. It seems like they peaked around noon. 

### Assignment 2.2























